### PR TITLE
Follow conjugation convention in `tree_dot`

### PR DESCRIPTION
**Pull request by Randl**
It may break something downstream unfortunately, so updating dependencies should be done carefully

### CODE REVIEW

**Comment by patrick-kidger** [comment]
Modulo failing tests -- not sure what's going on with those (?) -- this LGTM.
Once the tests are fixed we can check the Optimistix and Diffrax tests on this PR before merging it, and see if anything looks awry.

**Comment by patrick-kidger** [comment]
Yes, I think we should.

I can see that tests now pass -- are you happy with this PR / should I merge it?

**Comment by Randl** [comment]
I think I am.
Though one possibility to consider is to not do conjugation in `tree_dot` at all but rater leave it to caller, similarly to `jnp.dot`. This may clutter downstream code but will be consistent with the Jax/numpy semantics.

**Comment by patrick-kidger** [comment]
Merged, then!
And that's an interesting idea. In particular given the difficulties we faced in https://github.com/patrick-kidger/optimistix/pull/61, I can see that that might simplify things.

The decision is yours -- I'd be happy to make that change if you think that is what is best.

**Pull request merged**
